#!/bin/sh -e

cmd=$1
shift
case "$cmd" in
  get-version)
    head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    ;;
  bootstrap)
    sh ./autogen.sh
    ;;
  configure)
    ./configure --disable-docs $@
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
